name = "acearchive-keeper"
main = "build/index.js"
compatibility_date = "2025-11-06"

[build]
command = "cargo install -q worker-build && worker-build --release"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "acearchive-keeper"
database_id = "87b610c2-c265-4e2e-9070-b38739892317"
