name = "acearchive-keeper"
main = "build/index.js"
compatibility_date = "2025-11-06"

[build]
command = "cargo install -q worker-build && worker-build --release"

[observability]
enabled = true

[route]
pattern = "keeper-api.acearchive.lgbt"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "acearchive-keeper"
database_id = "936f8e3c-8b98-4f91-933c-ff4189ae96b0"
